version: '3'
services:
  mongodb:
    image: mongo:latest
    restart: unless-stopped
    volumes:
      - db:/data/db
  cache:
    image: redis:alpine
    restart: always
    ports:
      - '6379:6379'
    command: redis-server
    volumes:
      - cache:/data
  node-api:
    build: .
    ports:
      - "4000:4000"
    env_file:
      - ./.env
    depends_on:
      - mongodb
      - cache
    restart: unless-stopped
    stdin_open: true
    tty: true
    volumes:
      - ./:/src
volumes:
  db:
    driver: local
  cache:
    driver: local
